// <auto-generated />
namespace Joinup.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Reiniciodetodo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Reiniciodetodo));
        
        string IMigrationMetadata.Id
        {
            get { return "201809240942516_Reinicio de todo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
