// <auto-generated />
namespace Joinup.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Migración2611 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migración2611));
        
        string IMigrationMetadata.Id
        {
            get { return "201811260916316_Migración 26-11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
